apiVersion: batch/v1
kind: Job
metadata:
  name: producer
  labels:
    app: kafka-client
spec:
  template:
    spec:
      containers:
      - name: producer
        image: pjuarezd/kafka-client:latest
        command: ["./kafka-client",  "producer", "--topic", "example", "--file", "example/audit.csv"]
      restartPolicy: Never
  backoffLimit: 1
