kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
# featureGates:
#   "HugePages": false
nodes:
  - role: control-plane
    # kubeadmConfigPatches:
    # - |
    #   kind: ClusterConfiguration
    #   controllerManager:
    #     extraArgs:
    #       cluster-signing-duration: "4h0m0s"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: statefull
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: statefull
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: statefull
