kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
# featureGates:
#   "HugePages": false
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints:
          - effect: NoSchedule
            key: "CriticalAddonsOnly"
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints:
          - effect: NoSchedule
            key: "CriticalAddonsOnly"
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        taints:
          - effect: NoSchedule
            key: "CriticalAddonsOnly"
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
          node-labels: "ingress-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
    extraPortMappings:
    - containerPort: 80
      hostPort: 8081
      protocol: TCP
    - containerPort: 443
      hostPort: 4431
      protocol: TCP
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
          node-labels: "ingress-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
    extraPortMappings:
    - containerPort: 80
      hostPort: 8082
      protocol: TCP
    - containerPort: 443
      hostPort: 4432
      protocol: TCP
