kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta3
  kind: ClusterConfiguration
  networking:
    dnsDomain: "example.com"
nodes:
  - role: control-plane
    #image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    # kubeadmConfigPatches:
    # - |
    #   kind: ClusterConfiguration
    #   controllerManager:
    #     extraArgs:
    #       cluster-signing-duration: "4h0m0s"
  - role: worker
    #image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "type=storage"
        # taints:
        #   - effect: NoSchedule
        #     key: stateless
    extraPortMappings:
    - containerPort: 80
      hostPort: 8081
      protocol: TCP
    - containerPort: 443
      hostPort: 4431
      protocol: TCP
  - role: worker
   # image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "type=storage"
    extraPortMappings:
    - containerPort: 80
      hostPort: 8082
      protocol: TCP
    - containerPort: 443
      hostPort: 4432
      protocol: TCP
  - role: worker
   # image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=false"
    extraPortMappings:
    - containerPort: 80
      hostPort: 8083
      protocol: TCP
    - containerPort: 443
      hostPort: 4433
      protocol: TCP
  - role: worker
   # image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 8084
      protocol: TCP
    - containerPort: 443
      hostPort: 4434
      protocol: TCP
  - role: worker
   # image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
          node-labels: "ingress-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: statefull
    extraPortMappings:
    - containerPort: 80
      hostPort: 8085
      protocol: TCP
    - containerPort: 443
      hostPort: 4435
      protocol: TCP
  - role: worker
   # image: kindest/node:v1.20.15@sha256:a32bf55309294120616886b5338f95dd98a2f7231519c7dedcec32ba29699394
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "db-ready=true"
          node-labels: "ingress-ready=true"
        # taints:
        #   - effect: NoSchedule
        #     key: statefull
    extraPortMappings:
    - containerPort: 80
      hostPort: 8086
      protocol: TCP
    - containerPort: 443
      hostPort: 4436
      protocol: TCP
