apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: s3-connector
  labels:
    strimzi.io/cluster: connector-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    topics: example
    s3.region: us-east-1
    s3.bucket.name: kafka
    s3.part.size: 5242880
    flush.size: 20
    store.url: http://minio.minio-tenant-1.svc.cluster.local:80
    storage.class: io.confluent.connect.s3.storage.S3Storage
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    schema.generator.class: io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    schema.compatibility: NONE
