
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connector-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    strimzi.io/cluster: cl-01
spec:
  # jvmOptions:
  #   javaSystemProperties:
  #     - name: javax.net.debug
  #       value: ssl
      # - name: javax.net.ssl.trustStore
      #   value: /tmp/kafka/cluster.truststore.p12
      # - name: javax.net.ssl.trustStorePassword
      #   value: >
      #     "${CERTS_STORE_PASSWORD}"
      # - name: javax.net.ssl.trustStoreType
      #   value: PKCS12
  version: 3.2.0
  image: pjuarezd/minio-kafka-connector:test
  replicas: 1
  bootstrapServers: cl-01-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: cl-01-cluster-ca-cert
        certificate: ca.crt
      # - secretName: kube-root-ca
      #   certificate: ca.crt
      # - secretName: minio-tenant-1-ca-cert
      #   certificate: minio.minio-tenant-1.svc.cluster.local
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-connect
      certificate: user.crt
      key: user.key
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 10
  externalConfiguration:
    volumes:
      - name: minio-tenant-1-truststore
        secret:
          secretName: minio-tenant-1-truststore
    env:
      - name: KESTORE_SECRET
        valueFrom:
          secretKeyRef:
            name: minio-tenant-1-truststore
            key: truststore.password
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsAccessKey
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-creds
            key: awsSecretAccessKey
  config:
    group.id: connector-cluster
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
  # template:
  #   pod:
  #     securityContext:
  #       runAsUser: 0
  #       fsGroup: 0
    # connectContainer:
    #   env:
    #     - name: STORE_PASSWORD
    #       value: $(cat /tmp/strimzi-connect.properties | grep consumer.ssl.truststore.password | cut -d'=' -f2)
